"""Add po_id to ProductInstance

Revision ID: 2b1ad29d4b1e
Revises: a28171c76ff3
Create Date: 2025-06-08 00:57:07.694059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1ad29d4b1e'
down_revision = 'a28171c76ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('po_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_productinstance_po_id', 'purchase_order', ['po_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_productinstance_po_id', type_='foreignkey')
        batch_op.drop_column('po_id')

    # ### end Alembic commands ###
