"""add_login_tracking_to_user

Revision ID: 0041b46c1df4
Revises: 998ed86220e0
Create Date: 2026-03-26 10:03:17.232207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0041b46c1df4'
down_revision = '998ed86220e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('last_login_at')

    # ### end Alembic commands ###
