"""add_customer_order_status_index

Revision ID: 031055a347d6
Revises: t1r2a3c4k5s6
Create Date: 2026-03-23 15:12:55.177921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031055a347d6'
down_revision = 't1r2a3c4k5s6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_order_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_order_status'))

    # ### end Alembic commands ###
