"""Add tenant_id to Vendor, Customer, and Part

Revision ID: 15a1d995d134
Revises: fffad810de87
Create Date: 2025-06-25 01:28:00.524341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a1d995d134'
down_revision = 'fffad810de87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        # Skipping 'tenant_id' column in customer — already exists
        pass

    with op.batch_alter_table('part', schema=None) as batch_op:
        # Skipping 'tenant_id' column in part — already exists
        pass

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        # Skipping 'tenant_id' column in vendor — already exists
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
