"""add_expected_price_to_poi_numeric_asking_price

Revision ID: 1ae97b59bf00
Revises: s1m2a3r4t5p6
Create Date: 2026-03-24 13:17:08.625877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae97b59bf00'
down_revision = 's1m2a3r4t5p6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.alter_column('asking_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('purchase_order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_price', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('user_permission', schema=None) as batch_op:
        batch_op.alter_column('access_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'none'::character varying"))
        batch_op.drop_index(batch_op.f('ix_user_permission_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_user_permission_user_id'))
        # Immediately recreate the index — it is needed for every permission check on page load
        batch_op.create_index(batch_op.f('ix_user_permission_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_permission_user_id'))  # drop the one added in upgrade
        batch_op.create_index(batch_op.f('ix_user_permission_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_permission_tenant_id'), ['tenant_id'], unique=False)
        batch_op.alter_column('access_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'none'::character varying"))

    with op.batch_alter_table('purchase_order_item', schema=None) as batch_op:
        batch_op.drop_column('expected_price')

    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.alter_column('asking_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    # ### end Alembic commands ###
