"""add_instance_and_sale_indexes

Revision ID: 30905b0651c9
Revises: 586c400104db
Create Date: 2026-03-16 13:36:49.413703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30905b0651c9'
down_revision = '586c400104db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.create_index('ix_pi_tenant_sold_status', ['tenant_id', 'is_sold', 'status'], unique=False)

    with op.batch_alter_table('sale_transaction', schema=None) as batch_op:
        batch_op.create_index('ix_sale_transaction_customer_id', ['customer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_transaction', schema=None) as batch_op:
        batch_op.drop_index('ix_sale_transaction_customer_id')

    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.drop_index('ix_pi_tenant_sold_status')

    # ### end Alembic commands ###
