"""Add Tenant model

Revision ID: 3b8c8256f8da
Revises: 4ca3a50446cc
Create Date: 2025-06-24 23:19:46.401344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b8c8256f8da'
down_revision = '4ca3a50446cc'
branch_labels = None
depends_on = None


def upgrade():
    # Skipping creation of 'tenant' table — already exists
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant')
    # ### end Alembic commands ###
