"""Add TenantSettings model

Revision ID: 4ca3a50446cc
Revises: cb2f80d35b6a
Create Date: 2025-06-24 21:59:38.392910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca3a50446cc'
down_revision = 'cb2f80d35b6a'
branch_labels = None
depends_on = None


def upgrade():
    # Skipping creation of 'tenant_settings' table — already exists
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_settings')
    # ### end Alembic commands ###
