"""order_number_unique_per_tenant

Revision ID: 519c546375af
Revises: 0041b46c1df4
Create Date: 2026-03-26 10:34:43.015133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519c546375af'
down_revision = '0041b46c1df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_order_number'))
        batch_op.create_index(batch_op.f('ix_order_order_number'), ['order_number'], unique=False)
        batch_op.create_unique_constraint('uq_order_number_tenant', ['order_number', 'tenant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('uq_order_number_tenant', type_='unique')
        batch_op.drop_index(batch_op.f('ix_order_order_number'))
        batch_op.create_index(batch_op.f('ix_order_order_number'), ['order_number'], unique=True)

    # ### end Alembic commands ###
