"""add_superadmin_flag_and_tenant_management

Revision ID: 561966b249f5
Revises: dd3738bd944a
Create Date: 2026-03-27 17:21:23.939242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561966b249f5'
down_revision = 'dd3738bd944a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superadmin', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_superadmin')

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
