"""invoice_number_per_tenant_unique

Revision ID: 586c400104db
Revises: 95c9d2b5ac74
Create Date: 2026-03-16 13:35:03.119997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586c400104db'
down_revision = '95c9d2b5ac74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('invoice_invoice_number_key'), type_='unique')
        batch_op.create_unique_constraint('uix_invoice_number_tenant', ['invoice_number', 'tenant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint('uix_invoice_number_tenant', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('invoice_invoice_number_key'), ['invoice_number'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
