"""Add tenant_id to ProductInstance with FK name

Revision ID: 5c9b46474b78
Revises: d3e9215b1b53
Create Date: 2025-06-26 12:20:03.644180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9b46474b78'
down_revision = 'd3e9215b1b53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_product_instance_tenant_id', 'tenant', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_instance_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
