"""Add timezone field to Tenant

Revision ID: 5ea8b84d0a03
Revises: cba55c417bc3
Create Date: 2025-06-29 19:22:12.175573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea8b84d0a03'
down_revision = 'cba55c417bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
