"""add_returned_at_to_product_instance

Revision ID: 61432d72f0e3
Revises: 519c546375af
Create Date: 2026-03-26 11:25:11.351505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61432d72f0e3'
down_revision = '519c546375af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.drop_column('returned_at')

    # ### end Alembic commands ###
