"""add_credit_note_tenant_index

Revision ID: 7217c0936f8e
Revises: d2e3f4g5h6i7
Create Date: 2026-03-17 13:57:05.438551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7217c0936f8e'
down_revision = 'd2e3f4g5h6i7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_note_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_note_tenant_id'))

    # ### end Alembic commands ###
