"""Add asset_tag to ProductInstance

Revision ID: 75ed296038e6
Revises: 5c9b46474b78
Create Date: 2025-06-26 13:06:51.711916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ed296038e6'
down_revision = '5c9b46474b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_tag', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_product_instance_asset_tag'), ['asset_tag'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_instance_asset_tag'))
        batch_op.drop_column('asset_tag')

    # ### end Alembic commands ###
