"""rename return table to returns

Revision ID: 7d5975119750
Revises: d309e908ab03
Create Date: 2025-07-05 13:13:37.491238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5975119750'
down_revision = 'd309e908ab03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['product_instance.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('item_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_instance_asset_tag'))
        batch_op.drop_column('asset_tag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_tag', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_product_instance_asset_tag'), ['asset_tag'], unique=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('item_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.drop_table('returns')
    # ### end Alembic commands ###
