"""Add optional vendor fields

Revision ID: 8a6e0396bce0
Revises: 8c918e954036
Create Date: 2025-06-28 03:02:24.281316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6e0396bce0'
down_revision = '8c918e954036'
branch_labels = None
depends_on = None


def upgrade():
    # Skipping 'email', 'phone', and 'address' columns on vendor — already exist
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
