"""Add tenant_id to Invoice

Revision ID: 8c918e954036
Revises: d6190ce5af8e
Create Date: 2025-06-27 15:06:04.618193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c918e954036'
down_revision = 'd6190ce5af8e'
branch_labels = None
depends_on = None


def upgrade():
    # Skipping 'tenant_id' column and foreign key — already exist in invoice
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
