"""username_unique_per_tenant

Revision ID: 998ed86220e0
Revises: d9c40de175a2
Create Date: 2026-03-26 09:55:46.494476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998ed86220e0'
down_revision = 'd9c40de175a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('part_sale', schema=None) as batch_op:
        batch_op.alter_column('unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('product_process_log', schema=None) as batch_op:
        batch_op.create_index('ix_ppl_instance_id', ['product_instance_id'], unique=False)
        batch_op.create_index('ix_ppl_moved_at', ['moved_at'], unique=False)
        batch_op.create_index('ix_ppl_moved_by', ['moved_by'], unique=False)

    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.alter_column('price_at_sale',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('vat_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('sale_transaction', schema=None) as batch_op:
        batch_op.alter_column('price_at_sale',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=False)
        batch_op.create_unique_constraint('uq_user_username_tenant', ['username', 'tenant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_username_tenant', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    with op.batch_alter_table('sale_transaction', schema=None) as batch_op:
        batch_op.alter_column('price_at_sale',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.alter_column('vat_rate',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('price_at_sale',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('product_process_log', schema=None) as batch_op:
        batch_op.drop_index('ix_ppl_moved_by')
        batch_op.drop_index('ix_ppl_moved_at')
        batch_op.drop_index('ix_ppl_instance_id')

    with op.batch_alter_table('part_sale', schema=None) as batch_op:
        batch_op.alter_column('unit_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    # ### end Alembic commands ###
