"""Add action and note to ProductProcessLog

Revision ID: b02644c6a86f
Revises: cfa163ec697f
Create Date: 2025-06-22 17:53:46.588740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b02644c6a86f'
down_revision = 'cfa163ec697f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_process_log', schema=None) as batch_op:
        # Skipping 'action' and 'note' columns — they already exist
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_process_log', schema=None) as batch_op:
        batch_op.drop_column('note')
        batch_op.drop_column('action')

    # ### end Alembic commands ###
