"""Add shelf_bin to ProductInstance

Revision ID: b09c30b68c27
Revises: 142fd87886b5
Create Date: 2025-06-16 12:31:56.616876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b09c30b68c27'
down_revision = '142fd87886b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        # Skipping column creation because 'shelf_bin' already exists
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.drop_column('shelf_bin')

    # ### end Alembic commands ###
