"""Fix Product model with location_id foreign key

Revision ID: b19830a2c803
Revises: 75ed296038e6
Create Date: 2025-06-26 17:09:02.457982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19830a2c803'
down_revision = '75ed296038e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('serial', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('item_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('make', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('display', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cpu', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gpu1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gpu2', sa.String(length=100), nullable=True))
        batch_op.alter_column('ram',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_product_barcode'))
        batch_op.drop_index(batch_op.f('ix_product_name'))
        batch_op.create_index(batch_op.f('ix_product_asset'), ['asset'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_item_name'), ['item_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_serial'), ['serial'], unique=True)
        batch_op.drop_column('barcode')
        batch_op.drop_column('image_url')
        batch_op.drop_column('purchase_price')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('stock')
        batch_op.drop_column('storage')
        batch_op.drop_column('name')
        batch_op.drop_column('resolution')
        batch_op.drop_column('warranty_date')
        batch_op.drop_column('video_card')
        batch_op.drop_column('selling_price')
        batch_op.drop_column('model_number')
        batch_op.drop_column('processor')
        batch_op.drop_column('screen_size')
        batch_op.drop_column('low_stock_threshold')
        batch_op.drop_column('is_damaged')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_damaged', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('low_stock_threshold', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('screen_size', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('processor', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('model_number', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('selling_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('video_card', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('warranty_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('resolution', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('storage', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('stock', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('purchase_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('barcode', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_index(batch_op.f('ix_product_serial'))
        batch_op.drop_index(batch_op.f('ix_product_item_name'))
        batch_op.drop_index(batch_op.f('ix_product_asset'))
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_barcode'), ['barcode'], unique=1)
        batch_op.alter_column('ram',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('gpu2')
        batch_op.drop_column('gpu1')
        batch_op.drop_column('cpu')
        batch_op.drop_column('display')
        batch_op.drop_column('model')
        batch_op.drop_column('make')
        batch_op.drop_column('item_name')
        batch_op.drop_column('serial')
        batch_op.drop_column('asset')

    # ### end Alembic commands ###
