"""Fix Product model with location_id foreign key

Revision ID: b19830a2c803
Revises: 75ed296038e6
Create Date: 2025-06-26 17:09:02.457982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19830a2c803'
down_revision = '75ed296038e6'
branch_labels = None
depends_on = None


def upgrade():
    # Skipping all modifications to 'product' table — columns and indexes already exist
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_damaged', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('low_stock_threshold', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('screen_size', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('processor', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('model_number', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('selling_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('video_card', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('warranty_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('resolution', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('storage', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('stock', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('purchase_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('barcode', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_index(batch_op.f('ix_product_serial'))
        batch_op.drop_index(batch_op.f('ix_product_item_name'))
        batch_op.drop_index(batch_op.f('ix_product_asset'))
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_barcode'), ['barcode'], unique=1)
        batch_op.alter_column('ram',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('gpu2')
        batch_op.drop_column('gpu1')
        batch_op.drop_column('cpu')
        batch_op.drop_column('display')
        batch_op.drop_column('model')
        batch_op.drop_column('make')
        batch_op.drop_column('item_name')
        batch_op.drop_column('serial')
        batch_op.drop_column('asset')

    # ### end Alembic commands ###
