"""Add created_at to Product

Revision ID: c5a31d31d2db
Revises: f1918eeedc97
Create Date: 2025-06-26 23:33:22.315318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a31d31d2db'
down_revision = 'f1918eeedc97'
branch_labels = None
depends_on = None


def upgrade():
    # Skipping 'created_at' column and 'item_name' alteration — already applied
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('item_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
