"""Add idle_reason to ProductInstance

Revision ID: cb2f80d35b6a
Revises: d40a8daaa220
Create Date: 2025-06-22 23:58:58.883093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb2f80d35b6a'
down_revision = 'd40a8daaa220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        # Skipping 'idle_reason' column — already exists
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.drop_column('idle_reason')

    # ### end Alembic commands ###
