"""Add unique constraint to serial and asset in ProductInstance

Revision ID: cba55c417bc3
Revises: ea1b7ed5f273
Create Date: 2025-06-29 01:56:13.700955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba55c417bc3'
down_revision = 'ea1b7ed5f273'
branch_labels = None
depends_on = None


def upgrade():
    # Skipping 'serial' and 'asset' column changes — already exist
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_tag', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('serial_number', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_index(batch_op.f('ix_product_instance_serial'))
        batch_op.drop_index(batch_op.f('ix_product_instance_asset'))
        batch_op.create_index(batch_op.f('ix_product_instance_serial_number'), ['serial_number'], unique=1)
        batch_op.create_index(batch_op.f('ix_product_instance_asset_tag'), ['asset_tag'], unique=1)
        batch_op.drop_column('asset')
        batch_op.drop_column('serial')

    # ### end Alembic commands ###
