"""Add created_at to ProductInstance

Revision ID: cfa163ec697f
Revises: b09c30b68c27
Create Date: 2025-06-17 23:40:26.750377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa163ec697f'
down_revision = 'b09c30b68c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
