"""Add tenant_id to PurchaseOrder

Revision ID: d3e9215b1b53
Revises: 3550d14025d9
Create Date: 2025-06-25 10:26:42.436032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e9215b1b53'
down_revision = '3550d14025d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        # Skipping 'tenant_id' column and foreign key — already exist
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
