"""Add assigned_to_user_id to ProductInstance

Revision ID: d40a8daaa220
Revises: b02644c6a86f
Create Date: 2025-06-22 19:03:37.085205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd40a8daaa220'
down_revision = 'b02644c6a86f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_product_instance_assigned_to_user_id_user', 'user', ['assigned_to_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_instance_assigned_to_user_id_user', type_='foreignkey')
        batch_op.drop_column('assigned_to_user_id')

    # ### end Alembic commands ###
