"""Add note to ProductInstance

Revision ID: d6190ce5af8e
Revises: cc3fac6813b7
Create Date: 2025-06-27 01:50:41.404083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6190ce5af8e'
down_revision = 'cc3fac6813b7'
branch_labels = None
depends_on = None


def upgrade():
    # Skipping 'note' column addition — already exists in product_instance
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
