"""sync_index_names

Revision ID: d9c40de175a2
Revises: c3d4e5f6g7h8
Create Date: 2026-03-26 07:48:48.262356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c40de175a2'
down_revision = 'c3d4e5f6g7h8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_tenant_id'))

    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pi_bin_id_perf'))
        batch_op.drop_index(batch_op.f('ix_pi_location_id_perf'))
        batch_op.create_index('ix_pi_bin_id', ['bin_id'], unique=False)
        batch_op.create_index('ix_pi_location_id', ['location_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.drop_index('ix_pi_location_id')
        batch_op.drop_index('ix_pi_bin_id')
        batch_op.create_index(batch_op.f('ix_pi_location_id_perf'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pi_bin_id_perf'), ['bin_id'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###
