"""Rename serial_number and asset_tag to serial and asset in ProductInstance

Revision ID: ea1b7ed5f273
Revises: c0dca89a8f79
Create Date: 2025-06-29 00:42:29.440143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1b7ed5f273'
down_revision = 'c0dca89a8f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_tenant_settings_tenant_id', 'tenant', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tenant_settings_tenant_id', type_='foreignkey')

    # ### end Alembic commands ###
