"""initial

Revision ID: edd27c7e99ef
Revises: 
Create Date: 2025-07-03 11:39:58.587309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd27c7e99ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_name'), ['name'], unique=False)

    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_name'), ['name'], unique=True)

    op.create_table('part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('part_type', sa.String(length=64), nullable=True),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_part_part_number'), ['part_number'], unique=True)

    op.create_table('tenant_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name='fk_user_tenant_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'tenant_id', name='uq_username_per_tenant')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_name'), ['name'], unique=True)

    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=20), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('part_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.String(length=32), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'location_id', name='uix_part_location')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=100), nullable=True),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('display', sa.String(length=100), nullable=True),
    sa.Column('cpu', sa.String(length=100), nullable=True),
    sa.Column('ram', sa.String(length=100), nullable=True),
    sa.Column('gpu1', sa.String(length=100), nullable=True),
    sa.Column('gpu2', sa.String(length=100), nullable=True),
    sa.Column('disk1size', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_asset'), ['asset'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_item_name'), ['item_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_serial'), ['serial'], unique=True)

    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('expected_serials', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_table('po_import_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=100), nullable=False),
    sa.Column('asset', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('process_stage', sa.String(length=50), nullable=True),
    sa.Column('team_assigned', sa.String(length=100), nullable=True),
    sa.Column('idle_reason', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('shelf_bin', sa.String(length=64), nullable=True),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('is_sold', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name='fk_product_instance_tenant_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_instance_asset'), ['asset'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_instance_serial'), ['serial'], unique=True)

    op.create_table('customer_order_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_instance_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('process_stage', sa.String(length=50), nullable=True),
    sa.Column('team_assigned', sa.String(length=100), nullable=True),
    sa.Column('reserved_date', sa.DateTime(), nullable=True),
    sa.Column('delivered_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['product_instance_id'], ['product_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_process_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_instance_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.String(length=50), nullable=True),
    sa.Column('to_stage', sa.String(length=50), nullable=True),
    sa.Column('from_team', sa.String(length=100), nullable=True),
    sa.Column('to_team', sa.String(length=100), nullable=True),
    sa.Column('moved_by', sa.Integer(), nullable=True),
    sa.Column('moved_at', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['moved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_instance_id'], ['product_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_instance_id', sa.Integer(), nullable=False),
    sa.Column('price_at_sale', sa.Float(), nullable=False),
    sa.Column('vat_rate', sa.Float(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['product_instance_id'], ['product_instance.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_instance_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('price_at_sale', sa.Float(), nullable=False),
    sa.Column('date_sold', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['product_instance_id'], ['product_instance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_transaction')
    op.drop_table('sale_item')
    op.drop_table('product_process_log')
    op.drop_table('customer_order_tracking')
    with op.batch_alter_table('product_instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_instance_serial'))
        batch_op.drop_index(batch_op.f('ix_product_instance_asset'))

    op.drop_table('product_instance')
    op.drop_table('po_import_log')
    op.drop_table('purchase_order')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_serial'))
        batch_op.drop_index(batch_op.f('ix_product_item_name'))
        batch_op.drop_index(batch_op.f('ix_product_asset'))

    op.drop_table('product')
    op.drop_table('part_stock')
    op.drop_table('part_movement')
    op.drop_table('invoice')
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_name'))

    op.drop_table('vendor')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('tenant_settings')
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_part_part_number'))

    op.drop_table('part')
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_name'))

    op.drop_table('location')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_name'))

    op.drop_table('customer')
    op.drop_table('tenant')
    op.drop_table('sale')
    # ### end Alembic commands ###
