"""Add disk1size to Product

Revision ID: f1918eeedc97
Revises: 1c3ec6529e18
Create Date: 2025-06-26 22:52:15.380740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1918eeedc97'
down_revision = '1c3ec6529e18'
branch_labels = None
depends_on = None


def upgrade():
    # Skipping 'disk1size' column and item_name alteration — already applied
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('item_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('disk1size')

    # ### end Alembic commands ###
