"""add_trn_and_invoice_fields

Revision ID: fcdfe2f9f55f
Revises: 61432d72f0e3
Create Date: 2026-03-26 11:54:35.664596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdfe2f9f55f'
down_revision = '61432d72f0e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trn', sa.String(length=20), nullable=True))

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('po_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('delivery_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('supply_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('due_date')
        batch_op.drop_column('supply_date')
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('po_reference')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('trn')

    # ### end Alembic commands ###
